#!/bin/sh
#
# Test "umpf status" in various states.
#

# status with no operation in progress
umpf status 2>&1 | grep "No umpf in progress"

# start umpf tag that will fail on a3
umpf tag --version=3 series.conflict --remote=origin || test $? = 1

# status during a failed operation
umpf status 2>&1 | grep "umpf tag in progress"
umpf status 2>&1 | grep "base: base"
umpf status 2>&1 | grep "name: name"
umpf status 2>&1 | grep "done	a2"
umpf status 2>&1 | grep "FAILED	a3"
umpf status 2>&1 | grep "pending	b"
umpf status 2>&1 | grep "1/3 topics done"

# resolve and continue
git add a.txt
umpf continue

# status after completion
umpf status 2>&1 | grep "No umpf in progress"
